# Site settings
title: UniCredit github
email: marco.scavazza@unicredit.eu
description: > # this means to ignore newlines until "baseurl:"
 github Research & Open Innovation - UniCredit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://UniCredit.github.io" # the base hostname & protocol for your site
twitter_username: UniCredit_PR
github_username:  UniCredit

# Build settings
markdown: kramdown
