# Site settings
title: Marco Ska GitHub
email: pippo@pippo.eu
description: > # this means to ignore newlines until "baseurl:"
 Marco Ska - GitHub <br>Research & Open Innovation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marcoscavazza.github.io" # the base hostname & protocol for your site
twitter_username: @marcoscavazza
github_username:  MarcoScavazza

# Build settings
markdown: kramdown


# Enter your Mail User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: pippo
  list-id: pluto
